name: Push Image
on: [push]
  # push:
  #   tags:
  #     - 'v*.*.*'
jobs:
    setenv:
        runs-on: ubuntu-20.04
        steps:
          - name: Check env
            run: |
              echo 'Project: ${{ vars.HARBOR_PROJECT }} | HARBOR_URL: ${{vars.HARBOR_URL}} | HARBOR_S3_URL: ${{ vars.HARBOR_S3_URL }} '
              echo ' HARBOR_USER: ${{ vars.HARBOR_USER }} | HARBOR_SECRET: ${{ secrets.HARBOR_SECRET}} | HARBOR_S3_SECRET: ${{ secrets.HARBOR_S3_SECRET }} '