name: Push Image
on: [push]
  # push:
  #   tags:
  #     - 'v*.*.*'
jobs:
    setenv:
        runs-on: ubuntu-20.04
        steps:
          - name: Check env
            run: |
              echo $HARBOR_PROJECT
        outputs:
          tag_name: ${{ steps.getenv.outputs.tag_name }}